import Link from "next/link";
import "../globals.css";
import { Inter } from "next/font/google";
import { getPages } from "@/sanity/sanity-utils";
import page from "@/sanity/schemas/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Personal Website",
  description: "Generated by Next + Sainty",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-black p-4 drop-shadow">
          <nav className="px-2 flex items-center xl:mx-[24%] justify-between text-sm text-white">
            <Link href={"/"} className="text-lg font-bold hover:bg-blue-500 hover:rounded-md p-2">
              Hjem
            </Link>
            <div className="flex items-center gap-5">
              {pages.map((page) => (
                <Link
                  key={page._id}
                  href={`/${page.slug}`}
                  className="text-lg font-bold hover:bg-blue-500 rounded-md p-2"
                >
                  {page.title}
                </Link>
              ))}
            </div>
          </nav>
        </header>
        <main className="max-w-3xl mx-auto py-5">{children}</main>
      </body>
    </html>
  );
}
